### ISSUE TITLE
Testing party: when signing up, it says my email is taken when I have never signed up before.

### ISSUE THREAD

**Issue by emoltz** [gcivil-nyu-org/team-1-inperson#169]
<img width="554" alt="Screenshot 2022-11-19 at 2 18 35 PM" src="https://user-images.githubusercontent.com/33405530/202867770-c616842a-cbb4-4ee5-a612-9bf149799803.png">

**Comment by claudiaashao** [comment]
Hey Ethan, we used your NYU email to register the testing party account for your group(see testing doc), so it shows as taken. Did you use a different email?
