### ISSUE TITLE
The list of items are very far apart geographically.

### ISSUE THREAD

**Issue by emoltz** [gcivil-nyu-org/team-1-inperson#172]
<img width="403" alt="Screenshot 2022-11-19 at 3 15 42 PM" src="https://user-images.githubusercontent.com/33405530/202869838-7d5fea4a-ad78-4870-a5fd-1581c057ff5a.png">

**Comment by claudiaashao** [comment]
thank you for pointing this out! we'll upload more pins in the upcoming week and it will fix this issue.
