### ISSUE TITLE
Testing Party Issue: Map View Issue - Reloads page to current location Not working

### ISSUE THREAD

**Issue by Pooja-Codes** [gcivil-nyu-org/team-1-inperson#174]
_Testing Scenario:_ 
Map Page
View issue- _**Reloads page to current location/default location**_ Not working after clicking on the post.

OS Windows 11 || Browser Google Chrome
Username- test2

https://user-images.githubusercontent.com/87775823/202872889-9c7ba79c-f347-404f-b37a-5aa8486c7c18.mp4

**Comment by claudiaashao** [comment]
Hi Pooja, we haven't implemented the add update(post button) functionality yet. Will be working on it this sprint. Thanks!
