### ISSUE TITLE
Testing Party Issue: Map Report issue- Length Validation Require on Issue Description

### ISSUE THREAD

**Issue by Pooja-Codes** [gcivil-nyu-org/team-1-inperson#175]
_Testing Scenario:_
Map Page
Report issue- **Enter description and submit report** 

OS Windows 11 || Browser Google Chrome
Username- test2

https://user-images.githubusercontent.com/87775823/202873487-23aa24fc-37bd-4e39-9341-881e656a5108.mp4

**Comment by am11449** [comment]
Thank you for pointing this out! Working on a fix :)
