### ISSUE TITLE
Search Bar Fix

### ISSUE THREAD

**Issue by AdnanAhsanNYCity** [gcivil-nyu-org/team-1-inperson#183]
Search bar functionality seems to have issues. I attempted to search for E 86th street and it worked the first time, when i tried to search for another street after my first search, it would default back to look at the 34th street location.

**Comment by claudiaashao** [comment]
hey, we were trying on our website and did not experience the same issue. could you provide more detail on how it happened? thanks

**Comment by AdnanAhsanNYCity** [comment]
Hi, see your Slack, sent a vid of it.

**Comment by SarthakGagdani** [comment]
@AdnanAhsanNYCity 
I checked and It is working for east 86th street but not on E 86th St..(There are two suggestions for east 86th st in the suggestion wrapper).  I think E 86th St is geocoded wrongly to some other location by mapbox and we cannot change that.. it's a Mapbox issue and I see only for this location yet. 
Thanks for catching though!
