### ISSUE TITLE
kudos best bugs

### ISSUE THREAD

**Issue by claudiaashao** [gcivil-nyu-org/team-1-inperson#198]
Provide "kudos" for the best 3 GitHub issues your team received.One team member submit on behalf of team.
Begin after the testing feedback is complete for all teams.
Provide link to issue on Github and username for each bug.
Kudos count as extra credit for the student mentioned.
All kudos are due by next class - create a Google Sheet and share with professor and TA

Format:
1st Best Bug:link student name #173 
2nd Best Bug:link student name #181 
3rd Best Bug:link student name #175 (but lowkey #183 is a bigger bug if it's actually a bug)

**Comment by SNefertitiB** [comment]
Added the following to Dennis' google doc:
Pooja Patel
#173

Dinesh Kumar Saravanan
#181

Pooja Patel
#175
